### ISSUE TITLE
ref to myutil

### ISSUE THREAD

**Issue by obar1** [grdall/python-video-queue#1]
```
util==1.0.2


from myutil.BashColor import BashColor
from myutil.FileUtil import makeFiles
from myutil.InputUtil import extractArgs, getIdsFromInput, isNumber
from myutil.PrintUtil import printS, printLists
```

???

**Comment by gardehal** [comment]
myutil is a part of a Python package I've used. 
https://github.com/grdall/python-packages

If this is not used optimally I apologize, I'm experimenting with Python.

It was originally partially named "util" and I guess it stuck around in the pip-system. The requirements.txt were set by pipreqs. which likely refer to it as "util". Will attempt to fix.

**Comment by gardehal** [comment]
Hi, ran an installation on a VM and updated the README install guide with some extra steps for the util now renamed to grdUtil.
You will have to download it again if you have version lower than 1.1.0.

Let me know if this solves the issue.
